# Site settings
title: After Glow Brides
email: mikaela@afterglowbrides.com
description: EXCEPTIONAL BEAUTY GROOMING, LUXURY WEDDING FILMS & PHOTOGRAPHY IN THE UK & WORLDWIDE
baseurl: "/after-glow-brides" # the subpath of your site, e.g. /blog/
url: "http://www.afterglowbrides.com" # the base hostname & protocol for your site
github_username:  afterglowbrides
navigation:
- text: Home
  url: /
- text: Creators
  url: /creators/
- text: Latest
  url: /latest/
- text: Weddings
  url: /weddings/
- text: Love Shoot
  url: /love-shoot/
- text: Editorial
  url: /editorial/
- text: Testimonials
  url: /testimonials/
- text: Partners
  url: /partners/
- text: Contact
  url: /contact/

# Build settings
markdown: kramdown
